[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
gpui-rsx.workspace = true
locker-core = { path = "../locker-core" }
rust-embed = "8.12.0"

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
