[workspace]
resolver = "2"
members = ["crates/locker-core", "crates/sync", "crates/gui"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.lints.clippy]
all = "warn"

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "69e2130295c2649963eb639fc70b4f2ee8ea1624", package = "gpui" }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git", rev = "0f0ab35233212f8f3277028995caf0c41e13ee6c", package = "gpui-component" }

[patch.crates-io]
gpui = { git = "https://github.com/zed-industries/zed", rev = "69e2130295c2649963eb639fc70b4f2ee8ea1624", package = "gpui", version = "=0.2.2" }
